### ISSUE TITLE
Standardise `transId` vs `tranId` in payment results

### ISSUE THREAD

**Issue by tjwoon** [Nexstream/KonnectedPayCordova#1]
On Android, payment results are returned with a `transId` field. On iOS, the field is `tranId`.

**Comment by wedjohn57** [comment]
native need to change?

**Comment by tjwoon** [comment]
@wedjohn57 I think it is caused by [my own Android code](https://github.com/Nexstream/KonnectedPayCordova/blob/master/android/my.com.nexstream.konnectedpay/KonnectedPayCordova.java#L141)

I just want to compare against KonnectedPayJS before making the change.

**Comment by tjwoon** [comment]
Should standardise to `tranId` as KonnectedPayJS also uses that name.
